// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTdvrgJGskzBNUfLv9P9sgnftWd_xQFM',
    appId: '1:206359178622:web:182ab0fc7b409b252a572f',
    messagingSenderId: '206359178622',
    projectId: 'daril-y',
    authDomain: 'daril-y.firebaseapp.com',
    databaseURL: 'https://daril-y-default-rtdb.firebaseio.com',
    storageBucket: 'daril-y.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcmaft2cxQmPPKyvQRhtSEfF28yJH7ICo',
    appId: '1:206359178622:android:066bb25a54c184bc2a572f',
    messagingSenderId: '206359178622',
    projectId: 'daril-y',
    databaseURL: 'https://daril-y-default-rtdb.firebaseio.com',
    storageBucket: 'daril-y.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPKVlnIIEftqHIs3rq5DmV2y_n-8AifyE',
    appId: '1:206359178622:ios:59acad61e79dad442a572f',
    messagingSenderId: '206359178622',
    projectId: 'daril-y',
    databaseURL: 'https://daril-y-default-rtdb.firebaseio.com',
    storageBucket: 'daril-y.appspot.com',
    iosClientId:
        '206359178622-ve04trfcj77eqhc6tk6sg7f2jlj6u6bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPKVlnIIEftqHIs3rq5DmV2y_n-8AifyE',
    appId: '1:206359178622:ios:d8de01bc4cce6bf12a572f',
    messagingSenderId: '206359178622',
    projectId: 'daril-y',
    databaseURL: 'https://daril-y-default-rtdb.firebaseio.com',
    storageBucket: 'daril-y.appspot.com',
    iosClientId:
        '206359178622-dlldu78tc36tg9r5cgcqkh764ullun59.apps.googleusercontent.com',
    iosBundleId: 'com.example.y.RunnerTests',
  );
}
